#:kivy 2.1.0

App:
<App>:

<TetrisWidget>:
    cols: 10
    size_hint: (None, 1)  
    width: self.height/2  
    spacing: 2  
    padding: 2 
    canvas.before:
        Color:
            rgb: [0.1, 0.1, 0.1]
        Rectangle:
            size: self.size
            pos: self.pos

<Panel>:
    canvas.before:
        Color:
            rgb: 0.1, 0.1, 0.1
        Rectangle:
            size: self.size
            pos: self.pos